import { StyleSheet } from "react-native";
import { colors } from "./colors";

const styles = StyleSheet.create({
  alignCenter: { alignItems: "center" },
  bgBlack: { backgroundColor: colors.black },
  bgBlue500: { backgroundColor: colors.blue[500] },
  bgBlue600: { backgroundColor: colors.blue[600] },
  bgRed500: { backgroundColor: colors.red[500] },
  bgZinc800: { backgroundColor: colors.zinc[800] },
  bgZinc900: { backgroundColor: colors.zinc[900] },
  bgZinc950: { backgroundColor: colors.zinc[950] },
  border: { borderWidth: 1 },
  borderZinc800: { borderColor: colors.zinc[800] },
  flex1: { flex: 1 },
  flexRow: { flexDirection: "row" },
  fontBlack: { fontWeight: "900" },
  fontBold: { fontWeight: "bold" },
  gapX1: { columnGap: 4 },
  gapX2: { columnGap: 8 },
  gapX4: { columnGap: 16 },
  gapY1: { rowGap: 4 },
  gapY2: { rowGap: 8 },
  gapY4: { rowGap: 16 },
  itemsCenter: { alignItems: "center" },
  itemsStretch: { alignItems: "stretch" },
  justifyCenter: { justifyContent: "center" },
  mt1: { marginTop: 4 },
  mt3: { marginTop: 12 },
  p2: { padding: 8 },
  p4: { padding: 16 },
  px4: { paddingHorizontal: 16 },
  py1: { paddingVertical: 4 },
  py2: { paddingVertical: 8 },
  py4: { paddingVertical: 16 },
  py8: { paddingVertical: 32 },
  roundedFull: { borderRadius: 9999 },
  roundedLg: { borderRadius: 8 },
  roundedMd: { borderRadius: 4 },
  selfCenter: { alignSelf: "center" },
  selfStart: { alignSelf: "flex-start" },
  text2Xl: { fontSize: 24 },
  text3Xl: { fontSize: 32 },
  textBlue500: { color: colors.blue[500] },
  textCenter: { textAlign: "center" },
  textXs: { fontSize: 12 },
  textSm: { fontSize: 14 },
  textLg: { fontSize: 18 },
  textRed500: { color: colors.red[500] },
  textWhite: { color: colors.white },
  textXl: { fontSize: 20 },
  textZinc400: { color: colors.zinc[400] },
  w4_5: { width: "80%" },
  w9_10: { width: "90%" },
  wFull: { width: "100%" },
});

export const {
  alignCenter,
  bgBlack,
  bgBlue500, 
  bgBlue600,
  bgRed500,
  bgZinc800,
  bgZinc900,
  bgZinc950,
  border,
  borderZinc800,
  flex1,
  flexRow,
  fontBlack,
  fontBold,
  gapX1,
  gapX2,
  gapX4,
  gapY1,
  gapY2,
  gapY4,
  itemsCenter, 
  itemsStretch,
  justifyCenter,
  mt1,
  mt3,
  p2,
  p4,
  px4,
  py1,
  py2,
  py4,
  py8,
  roundedFull,
  roundedLg,
  roundedMd, 
  selfCenter,
  selfStart,
  text2Xl,
  text3Xl,
  textBlue500,
  textCenter,
  textLg,
  textRed500,
  textSm,
  textWhite,
  textXl,
  textXs,
  textZinc400, 
  w4_5,
  w9_10,
  wFull
} = styles;